syntax_check_task:
  description: >
    Analyze the provided Java code for syntax issues, formatting errors, and code style violations.
  expected_output: >
    A list of syntax/style problems found in the code with line references and suggestions.
  agent: syntax_checker
  output_file: output/syntax_check.md

design_review_task:
  description: >
    Review the design and structure of the Java code, focusing on modularity, OOP, and SOLID principles.
  expected_output: >
    An evaluation of design strengths and weaknesses with improvement recommendations.
  agent: design_reviewer
  output_file: output/design_review.md

summary_task:
  description: >
    Summarize the findings from the syntax and design reviewers into a clear, actionable report for the developer.
  expected_output: >
    A concise report that includes highlights from both reviews, categorized by severity or priority.
  agent: summary_agent
  context: 
    - syntax_check_task
    - design_review_task
  output_file: output/feedback.md
